-- -- Insert seed votes
-- INSERT INTO votes (user_id, chapter_id) VALUES
--                                           (1, 1),
--                                           (2, 2),
--                                           (3, 3);
